# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thoughts of a programmer
email: kishu.agarwal1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Written with passion
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  - Gemfile
  - Gemfile.lock

github:
  url:               "https://kishuagarwal.github.io"
author:
  name:              "Kishu Agarwal"
  email:             "kishu.agarwal1@gmail.com"
  twitter:           "Agarwal1Kishu"
  github:            "kishuagarwal"
  facebook:          "kishuagarwal"
  linkedin:          "kishu-agarwal-5045359b"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
